/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionForm {
  'bankAccountNumber' : string,
  'orphanedAndDestitute' : boolean,
  'studentEmail' : string,
  'hasEShikshakosh' : boolean,
  'subjects' : SubjectSelection,
  'previousSchool' : string,
  'ifscCode' : string,
  'marksObtained' : bigint,
  'dateOfBirth' : bigint,
  'eShikshakoshNumber' : string,
  'caste' : string,
  'passingYear' : bigint,
  'apparNumber' : string,
  'accountHolderName' : string,
  'passingDivision' : PassingDivision,
  'studentPhone' : string,
  'religionOther' : string,
  'studentPen' : string,
  'photoUrl' : [] | [string],
  'mothersOccupation' : string,
  'policeStation' : string,
  'fathersName' : string,
  'bankName' : BankName,
  'district' : string,
  'mothersName' : string,
  'state' : State,
  'fathersContact' : string,
  'aadharNumber' : string,
  'handicapType' : [] | [string],
  'village' : string,
  'gender' : Gender,
  'physicallyHandicapped' : boolean,
  'category' : Category,
  'pinCode' : string,
  'previousRollNo' : string,
  'block' : string,
  'postOffice' : string,
  'mothersGuardianContact' : string,
  'guardianDeclaration' : boolean,
  'religion' : Religion,
  'fathersAadhaar' : string,
  'documentsChecklist' : DocumentsChecklist,
  'annualFamilyIncome' : string,
  'handicapPercentage' : [] | [bigint],
  'fathersOccupation' : string,
  'previousExam' : string,
  'hasPenAndApaar' : boolean,
  'mothersAadhaar' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export type BankName = { 'other' : null } |
  { 'finoPaymentBank' : null } |
  { 'dakshinBiharGraminBank' : null } |
  { 'indianPostPaymentBank' : null } |
  { 'madhyaBiharGraminBank' : null } |
  { 'stateBankOfIndia' : null } |
  { 'unionBankOfIndia' : null } |
  { 'punjabNationalBank' : null };
export type Category = { 'bc' : null } |
  { 'sc' : null } |
  { 'st' : null } |
  { 'ebc' : null } |
  { 'general' : null };
export type Class = { 'class09th' : null } |
  { 'class10th' : null } |
  { 'class11th' : null } |
  { 'class12th' : null };
export interface DocumentsChecklist {
  'mothersAadhaarCard' : boolean,
  'previousMarksheets' : boolean,
  'casteCertificate' : boolean,
  'deathCertificate' : boolean,
  'fathersAadhaarCard' : boolean,
  'residenceCertificate' : boolean,
  'incomeCertificate' : boolean,
  'studentAadhaarCard' : boolean,
  'transferCertificate' : boolean,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type PassingDivision = { 'first' : null } |
  { 'third' : null } |
  { 'second' : null };
export type Religion = { 'hinduism' : null } |
  { 'other' : null } |
  { 'christianity' : null } |
  { 'buddhism' : null } |
  { 'islam' : null };
export type State = { 'other' : null } |
  { 'bihar' : null } |
  { 'jharkhand' : null };
export type Stream = { 'arts' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export interface Student {
  'status' : ApplicationStatus,
  'principal' : Principal,
  'form' : [] | [AdmissionForm],
  '_class' : Class,
  'password' : string,
  'name' : string,
  'rejectionReason' : [] | [string],
  'email' : string,
  'admissionNumber' : string,
  'registrationDate' : Time,
}
export interface SubjectSelection {
  'mil' : [] | [string],
  'sil' : [] | [string],
  'extraSubject' : [] | [string],
  'stream' : [] | [Stream],
  'additionalSubject' : [] | [string],
  'compulsoryGroup1' : [] | [string],
  'compulsoryGroup2' : [] | [string],
  'electiveSubjects' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  '_class' : Class,
  'name' : string,
  'email' : string,
  'isStudent' : boolean,
}
export interface _SERVICE {
  'approveApplication' : ActorMethod<[string], undefined>,
  'approveApplicationForAdmin' : ActorMethod<[string, string], undefined>,
  'generateOtp' : ActorMethod<[string], string>,
  'getAdmissionNumber' : ActorMethod<[string], string>,
  'getAllAdmissionNumbers' : ActorMethod<[], Array<[string, string]>>,
  'getAllApplications' : ActorMethod<[], Array<Student>>,
  'getAllApplicationsForAdmin' : ActorMethod<[string], Array<Student>>,
  'getAllApprovedApplications' : ActorMethod<[], Array<Student>>,
  'getAllPendingApplications' : ActorMethod<[], Array<Student>>,
  'getAllRejectedApplications' : ActorMethod<[], Array<Student>>,
  'getApplicationStatus' : ActorMethod<[string], ApplicationStatus>,
  'getApplicationsSortedByDate' : ActorMethod<[], Array<Student>>,
  'getCallerStudent' : ActorMethod<[], [] | [Student]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getDraftData' : ActorMethod<[string], [] | [AdmissionForm]>,
  'getStudent' : ActorMethod<[string], Student>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'loginStudent' : ActorMethod<[string, string], boolean>,
  'registerStudent' : ActorMethod<[Class, string, string, string], string>,
  'rejectApplication' : ActorMethod<[string], undefined>,
  'rejectApplicationForAdmin' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'resetPassword' : ActorMethod<[string, string, string], undefined>,
  'resetPasswordDirect' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDraft' : ActorMethod<[string, AdmissionForm], undefined>,
  'submitForm' : ActorMethod<[string, AdmissionForm], undefined>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];