/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const Stream = IDL.Variant({
  'arts' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const SubjectSelection = IDL.Record({
  'mil' : IDL.Opt(IDL.Text),
  'sil' : IDL.Opt(IDL.Text),
  'extraSubject' : IDL.Opt(IDL.Text),
  'stream' : IDL.Opt(Stream),
  'additionalSubject' : IDL.Opt(IDL.Text),
  'compulsoryGroup1' : IDL.Opt(IDL.Text),
  'compulsoryGroup2' : IDL.Opt(IDL.Text),
  'electiveSubjects' : IDL.Vec(IDL.Text),
});
export const PassingDivision = IDL.Variant({
  'first' : IDL.Null,
  'third' : IDL.Null,
  'second' : IDL.Null,
});
export const BankName = IDL.Variant({
  'other' : IDL.Null,
  'finoPaymentBank' : IDL.Null,
  'dakshinBiharGraminBank' : IDL.Null,
  'indianPostPaymentBank' : IDL.Null,
  'madhyaBiharGraminBank' : IDL.Null,
  'stateBankOfIndia' : IDL.Null,
  'unionBankOfIndia' : IDL.Null,
  'punjabNationalBank' : IDL.Null,
});
export const State = IDL.Variant({
  'other' : IDL.Null,
  'bihar' : IDL.Null,
  'jharkhand' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Category = IDL.Variant({
  'bc' : IDL.Null,
  'sc' : IDL.Null,
  'st' : IDL.Null,
  'ebc' : IDL.Null,
  'general' : IDL.Null,
});
export const Religion = IDL.Variant({
  'hinduism' : IDL.Null,
  'other' : IDL.Null,
  'christianity' : IDL.Null,
  'buddhism' : IDL.Null,
  'islam' : IDL.Null,
});
export const DocumentsChecklist = IDL.Record({
  'mothersAadhaarCard' : IDL.Bool,
  'previousMarksheets' : IDL.Bool,
  'casteCertificate' : IDL.Bool,
  'deathCertificate' : IDL.Bool,
  'fathersAadhaarCard' : IDL.Bool,
  'residenceCertificate' : IDL.Bool,
  'incomeCertificate' : IDL.Bool,
  'studentAadhaarCard' : IDL.Bool,
  'transferCertificate' : IDL.Bool,
});
export const AdmissionForm = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'orphanedAndDestitute' : IDL.Bool,
  'studentEmail' : IDL.Text,
  'hasEShikshakosh' : IDL.Bool,
  'subjects' : SubjectSelection,
  'previousSchool' : IDL.Text,
  'ifscCode' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'dateOfBirth' : IDL.Int,
  'eShikshakoshNumber' : IDL.Text,
  'caste' : IDL.Text,
  'passingYear' : IDL.Nat,
  'apparNumber' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'passingDivision' : PassingDivision,
  'studentPhone' : IDL.Text,
  'religionOther' : IDL.Text,
  'studentPen' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'mothersOccupation' : IDL.Text,
  'policeStation' : IDL.Text,
  'fathersName' : IDL.Text,
  'bankName' : BankName,
  'district' : IDL.Text,
  'mothersName' : IDL.Text,
  'state' : State,
  'fathersContact' : IDL.Text,
  'aadharNumber' : IDL.Text,
  'handicapType' : IDL.Opt(IDL.Text),
  'village' : IDL.Text,
  'gender' : Gender,
  'physicallyHandicapped' : IDL.Bool,
  'category' : Category,
  'pinCode' : IDL.Text,
  'previousRollNo' : IDL.Text,
  'block' : IDL.Text,
  'postOffice' : IDL.Text,
  'mothersGuardianContact' : IDL.Text,
  'guardianDeclaration' : IDL.Bool,
  'religion' : Religion,
  'fathersAadhaar' : IDL.Text,
  'documentsChecklist' : DocumentsChecklist,
  'annualFamilyIncome' : IDL.Text,
  'handicapPercentage' : IDL.Opt(IDL.Nat),
  'fathersOccupation' : IDL.Text,
  'previousExam' : IDL.Text,
  'hasPenAndApaar' : IDL.Bool,
  'mothersAadhaar' : IDL.Text,
});
export const Class = IDL.Variant({
  'class09th' : IDL.Null,
  'class10th' : IDL.Null,
  'class11th' : IDL.Null,
  'class12th' : IDL.Null,
});
export const Time = IDL.Int;
export const Student = IDL.Record({
  'status' : ApplicationStatus,
  'principal' : IDL.Principal,
  'form' : IDL.Opt(AdmissionForm),
  '_class' : Class,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'registrationDate' : Time,
});
export const UserProfile = IDL.Record({
  '_class' : Class,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'isStudent' : IDL.Bool,
});

export const idlService = IDL.Service({
  'approveApplication' : IDL.Func([IDL.Text], [], []),
  'approveApplicationForAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAdmissionNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAllAdmissionNumbers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllApplicationsForAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'getAllApprovedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllPendingApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllRejectedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Text], [ApplicationStatus], ['query']),
  'getApplicationsSortedByDate' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerStudent' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDraftData' : IDL.Func([IDL.Text], [IDL.Opt(AdmissionForm)], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func(
      [Class, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'rejectApplication' : IDL.Func([IDL.Text], [], []),
  'rejectApplicationForAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'resetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'resetPasswordDirect' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDraft' : IDL.Func([IDL.Text, AdmissionForm], [], []),
  'submitForm' : IDL.Func([IDL.Text, AdmissionForm], [], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Stream = IDL.Variant({
    'arts' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const SubjectSelection = IDL.Record({
    'mil' : IDL.Opt(IDL.Text),
    'sil' : IDL.Opt(IDL.Text),
    'extraSubject' : IDL.Opt(IDL.Text),
    'stream' : IDL.Opt(Stream),
    'additionalSubject' : IDL.Opt(IDL.Text),
    'compulsoryGroup1' : IDL.Opt(IDL.Text),
    'compulsoryGroup2' : IDL.Opt(IDL.Text),
    'electiveSubjects' : IDL.Vec(IDL.Text),
  });
  const PassingDivision = IDL.Variant({
    'first' : IDL.Null,
    'third' : IDL.Null,
    'second' : IDL.Null,
  });
  const BankName = IDL.Variant({
    'other' : IDL.Null,
    'finoPaymentBank' : IDL.Null,
    'dakshinBiharGraminBank' : IDL.Null,
    'indianPostPaymentBank' : IDL.Null,
    'madhyaBiharGraminBank' : IDL.Null,
    'stateBankOfIndia' : IDL.Null,
    'unionBankOfIndia' : IDL.Null,
    'punjabNationalBank' : IDL.Null,
  });
  const State = IDL.Variant({
    'other' : IDL.Null,
    'bihar' : IDL.Null,
    'jharkhand' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Category = IDL.Variant({
    'bc' : IDL.Null,
    'sc' : IDL.Null,
    'st' : IDL.Null,
    'ebc' : IDL.Null,
    'general' : IDL.Null,
  });
  const Religion = IDL.Variant({
    'hinduism' : IDL.Null,
    'other' : IDL.Null,
    'christianity' : IDL.Null,
    'buddhism' : IDL.Null,
    'islam' : IDL.Null,
  });
  const DocumentsChecklist = IDL.Record({
    'mothersAadhaarCard' : IDL.Bool,
    'previousMarksheets' : IDL.Bool,
    'casteCertificate' : IDL.Bool,
    'deathCertificate' : IDL.Bool,
    'fathersAadhaarCard' : IDL.Bool,
    'residenceCertificate' : IDL.Bool,
    'incomeCertificate' : IDL.Bool,
    'studentAadhaarCard' : IDL.Bool,
    'transferCertificate' : IDL.Bool,
  });
  const AdmissionForm = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'orphanedAndDestitute' : IDL.Bool,
    'studentEmail' : IDL.Text,
    'hasEShikshakosh' : IDL.Bool,
    'subjects' : SubjectSelection,
    'previousSchool' : IDL.Text,
    'ifscCode' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'dateOfBirth' : IDL.Int,
    'eShikshakoshNumber' : IDL.Text,
    'caste' : IDL.Text,
    'passingYear' : IDL.Nat,
    'apparNumber' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'passingDivision' : PassingDivision,
    'studentPhone' : IDL.Text,
    'religionOther' : IDL.Text,
    'studentPen' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'mothersOccupation' : IDL.Text,
    'policeStation' : IDL.Text,
    'fathersName' : IDL.Text,
    'bankName' : BankName,
    'district' : IDL.Text,
    'mothersName' : IDL.Text,
    'state' : State,
    'fathersContact' : IDL.Text,
    'aadharNumber' : IDL.Text,
    'handicapType' : IDL.Opt(IDL.Text),
    'village' : IDL.Text,
    'gender' : Gender,
    'physicallyHandicapped' : IDL.Bool,
    'category' : Category,
    'pinCode' : IDL.Text,
    'previousRollNo' : IDL.Text,
    'block' : IDL.Text,
    'postOffice' : IDL.Text,
    'mothersGuardianContact' : IDL.Text,
    'guardianDeclaration' : IDL.Bool,
    'religion' : Religion,
    'fathersAadhaar' : IDL.Text,
    'documentsChecklist' : DocumentsChecklist,
    'annualFamilyIncome' : IDL.Text,
    'handicapPercentage' : IDL.Opt(IDL.Nat),
    'fathersOccupation' : IDL.Text,
    'previousExam' : IDL.Text,
    'hasPenAndApaar' : IDL.Bool,
    'mothersAadhaar' : IDL.Text,
  });
  const Class = IDL.Variant({
    'class09th' : IDL.Null,
    'class10th' : IDL.Null,
    'class11th' : IDL.Null,
    'class12th' : IDL.Null,
  });
  const Time = IDL.Int;
  const Student = IDL.Record({
    'status' : ApplicationStatus,
    'principal' : IDL.Principal,
    'form' : IDL.Opt(AdmissionForm),
    '_class' : Class,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'registrationDate' : Time,
  });
  const UserProfile = IDL.Record({
    '_class' : Class,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'isStudent' : IDL.Bool,
  });
  
  return IDL.Service({
    'approveApplication' : IDL.Func([IDL.Text], [], []),
    'approveApplicationForAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAdmissionNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAllAdmissionNumbers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllApplicationsForAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getAllApprovedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllPendingApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllRejectedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getApplicationStatus' : IDL.Func(
        [IDL.Text],
        [ApplicationStatus],
        ['query'],
      ),
    'getApplicationsSortedByDate' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerStudent' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDraftData' : IDL.Func([IDL.Text], [IDL.Opt(AdmissionForm)], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func(
        [Class, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'rejectApplication' : IDL.Func([IDL.Text], [], []),
    'rejectApplicationForAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'resetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'resetPasswordDirect' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDraft' : IDL.Func([IDL.Text, AdmissionForm], [], []),
    'submitForm' : IDL.Func([IDL.Text, AdmissionForm], [], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };