/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubjectSelection {
    mil?: string;
    sil?: string;
    extraSubject?: string;
    stream?: Stream;
    additionalSubject?: string;
    compulsoryGroup1?: string;
    compulsoryGroup2?: string;
    electiveSubjects: Array<string>;
}
export type Time = bigint;
export interface Student {
    status: ApplicationStatus;
    principal: Principal;
    form?: AdmissionForm;
    _class: Class;
    password: string;
    name: string;
    rejectionReason?: string;
    email: string;
    admissionNumber: string;
    registrationDate: Time;
}
export interface DocumentsChecklist {
    mothersAadhaarCard: boolean;
    previousMarksheets: boolean;
    casteCertificate: boolean;
    deathCertificate: boolean;
    fathersAadhaarCard: boolean;
    residenceCertificate: boolean;
    incomeCertificate: boolean;
    studentAadhaarCard: boolean;
    transferCertificate: boolean;
}
export interface AdmissionForm {
    bankAccountNumber: string;
    orphanedAndDestitute: boolean;
    studentEmail: string;
    hasEShikshakosh: boolean;
    subjects: SubjectSelection;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    caste: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: PassingDivision;
    studentPhone: string;
    religionOther: string;
    studentPen: string;
    photoUrl?: string;
    mothersOccupation: string;
    policeStation: string;
    fathersName: string;
    bankName: BankName;
    district: string;
    mothersName: string;
    state: State;
    fathersContact: string;
    aadharNumber: string;
    handicapType?: string;
    village: string;
    gender: Gender;
    physicallyHandicapped: boolean;
    category: Category;
    pinCode: string;
    previousRollNo: string;
    block: string;
    postOffice: string;
    mothersGuardianContact: string;
    guardianDeclaration: boolean;
    religion: Religion;
    fathersAadhaar: string;
    documentsChecklist: DocumentsChecklist;
    annualFamilyIncome: string;
    handicapPercentage?: bigint;
    fathersOccupation: string;
    previousExam: string;
    hasPenAndApaar: boolean;
    mothersAadhaar: string;
}
export interface UserProfile {
    _class: Class;
    name: string;
    email: string;
    isStudent: boolean;
}
export enum ApplicationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    draft = "draft"
}
export enum BankName {
    other = "other",
    finoPaymentBank = "finoPaymentBank",
    dakshinBiharGraminBank = "dakshinBiharGraminBank",
    indianPostPaymentBank = "indianPostPaymentBank",
    madhyaBiharGraminBank = "madhyaBiharGraminBank",
    stateBankOfIndia = "stateBankOfIndia",
    unionBankOfIndia = "unionBankOfIndia",
    punjabNationalBank = "punjabNationalBank"
}
export enum Category {
    bc = "bc",
    sc = "sc",
    st = "st",
    ebc = "ebc",
    general = "general"
}
export enum Class {
    class09th = "class09th",
    class10th = "class10th",
    class11th = "class11th",
    class12th = "class12th"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum PassingDivision {
    first = "first",
    third = "third",
    second = "second"
}
export enum Religion {
    hinduism = "hinduism",
    other = "other",
    christianity = "christianity",
    buddhism = "buddhism",
    islam = "islam"
}
export enum State {
    other = "other",
    bihar = "bihar",
    jharkhand = "jharkhand"
}
export enum Stream {
    arts = "arts",
    commerce = "commerce",
    science = "science"
}
export interface backendInterface {
    approveApplication(email: string): Promise<void>;
    approveApplicationForAdmin(email: string, adminPassword: string): Promise<void>;
    generateOtp(email: string): Promise<string>;
    getAdmissionNumber(email: string): Promise<string>;
    getAllAdmissionNumbers(): Promise<Array<[string, string]>>;
    getAllApplications(): Promise<Array<Student>>;
    getAllApplicationsForAdmin(adminPassword: string): Promise<Array<Student>>;
    getAllApprovedApplications(): Promise<Array<Student>>;
    getAllPendingApplications(): Promise<Array<Student>>;
    getAllRejectedApplications(): Promise<Array<Student>>;
    getApplicationStatus(email: string): Promise<ApplicationStatus>;
    getApplicationsSortedByDate(): Promise<Array<Student>>;
    getCallerStudent(): Promise<Student | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getDraftData(email: string): Promise<AdmissionForm | null>;
    getStudent(email: string): Promise<Student>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    loginStudent(email: string, password: string): Promise<boolean>;
    registerStudent(_class: Class, name: string, email: string, password: string): Promise<string>;
    rejectApplication(email: string): Promise<void>;
    rejectApplicationForAdmin(email: string, adminPassword: string, rejectionReason: string): Promise<void>;
    resetPassword(email: string, otp: string, newPassword: string): Promise<void>;
    resetPasswordDirect(email: string, newPassword: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDraft(email: string, form: AdmissionForm): Promise<void>;
    submitForm(email: string, form: AdmissionForm): Promise<void>;
    verifyOtp(email: string, otp: string): Promise<boolean>;
}
import type { AdmissionForm as _AdmissionForm, ApplicationStatus as _ApplicationStatus, BankName as _BankName, Category as _Category, Class as _Class, DocumentsChecklist as _DocumentsChecklist, Gender as _Gender, PassingDivision as _PassingDivision, Religion as _Religion, State as _State, Stream as _Stream, Student as _Student, SubjectSelection as _SubjectSelection, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0);
            return result;
        }
    }
    async approveApplicationForAdmin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplicationForAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplicationForAdmin(arg0, arg1);
            return result;
        }
    }
    async generateOtp(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0);
            return result;
        }
    }
    async getAdmissionNumber(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmissionNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmissionNumber(arg0);
            return result;
        }
    }
    async getAllAdmissionNumbers(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdmissionNumbers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdmissionNumbers();
            return result;
        }
    }
    async getAllApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllApplicationsForAdmin(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplicationsForAdmin(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplicationsForAdmin(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllApprovedApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRejectedApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRejectedApplications();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRejectedApplications();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationStatus(arg0: string): Promise<ApplicationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationStatus(arg0);
                return from_candid_ApplicationStatus_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationStatus(arg0);
            return from_candid_ApplicationStatus_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationsSortedByDate(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsSortedByDate();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsSortedByDate();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerStudent(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStudent();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStudent();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDraftData(arg0: string): Promise<AdmissionForm | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraftData(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraftData(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Student_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Student_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginStudent(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginStudent(arg0, arg1);
            return result;
        }
    }
    async registerStudent(arg0: Class, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(to_candid_Class_n34(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(to_candid_Class_n34(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async rejectApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplication(arg0);
            return result;
        }
    }
    async rejectApplicationForAdmin(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplicationForAdmin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplicationForAdmin(arg0, arg1, arg2);
            return result;
        }
    }
    async resetPassword(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async resetPasswordDirect(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordDirect(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordDirect(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDraft(arg0: string, arg1: AdmissionForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraft(arg0, to_candid_AdmissionForm_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraft(arg0, to_candid_AdmissionForm_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitForm(arg0: string, arg1: AdmissionForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForm(arg0, to_candid_AdmissionForm_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForm(arg0, to_candid_AdmissionForm_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdmissionForm_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionForm): AdmissionForm {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_BankName_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankName): BankName {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Class_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Class): Class {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PassingDivision_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PassingDivision): PassingDivision {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Religion_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Religion): Religion {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_State_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _State): State {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Stream_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stream): Stream {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectSelection_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectSelection): SubjectSelection {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stream]): Stream | null {
    return value.length === 0 ? null : from_candid_Stream_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdmissionForm]): AdmissionForm | null {
    return value.length === 0 ? null : from_candid_AdmissionForm_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mil: [] | [string];
    sil: [] | [string];
    extraSubject: [] | [string];
    stream: [] | [_Stream];
    additionalSubject: [] | [string];
    compulsoryGroup1: [] | [string];
    compulsoryGroup2: [] | [string];
    electiveSubjects: Array<string>;
}): {
    mil?: string;
    sil?: string;
    extraSubject?: string;
    stream?: Stream;
    additionalSubject?: string;
    compulsoryGroup1?: string;
    compulsoryGroup2?: string;
    electiveSubjects: Array<string>;
} {
    return {
        mil: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.mil)),
        sil: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.sil)),
        extraSubject: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.extraSubject)),
        stream: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.stream)),
        additionalSubject: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.additionalSubject)),
        compulsoryGroup1: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.compulsoryGroup1)),
        compulsoryGroup2: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.compulsoryGroup2)),
        electiveSubjects: value.electiveSubjects
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApplicationStatus;
    principal: Principal;
    form: [] | [_AdmissionForm];
    _class: _Class;
    password: string;
    name: string;
    rejectionReason: [] | [string];
    email: string;
    admissionNumber: string;
    registrationDate: _Time;
}): {
    status: ApplicationStatus;
    principal: Principal;
    form?: AdmissionForm;
    _class: Class;
    password: string;
    name: string;
    rejectionReason?: string;
    email: string;
    admissionNumber: string;
    registrationDate: Time;
} {
    return {
        status: from_candid_ApplicationStatus_n4(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        form: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.form)),
        _class: from_candid_Class_n28(_uploadFile, _downloadFile, value._class),
        password: value.password,
        name: value.name,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.rejectionReason)),
        email: value.email,
        admissionNumber: value.admissionNumber,
        registrationDate: value.registrationDate
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _class: _Class;
    name: string;
    email: string;
    isStudent: boolean;
}): {
    _class: Class;
    name: string;
    email: string;
    isStudent: boolean;
} {
    return {
        _class: from_candid_Class_n28(_uploadFile, _downloadFile, value._class),
        name: value.name,
        email: value.email,
        isStudent: value.isStudent
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: string;
    orphanedAndDestitute: boolean;
    studentEmail: string;
    hasEShikshakosh: boolean;
    subjects: _SubjectSelection;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    caste: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: _PassingDivision;
    studentPhone: string;
    religionOther: string;
    studentPen: string;
    photoUrl: [] | [string];
    mothersOccupation: string;
    policeStation: string;
    fathersName: string;
    bankName: _BankName;
    district: string;
    mothersName: string;
    state: _State;
    fathersContact: string;
    aadharNumber: string;
    handicapType: [] | [string];
    village: string;
    gender: _Gender;
    physicallyHandicapped: boolean;
    category: _Category;
    pinCode: string;
    previousRollNo: string;
    block: string;
    postOffice: string;
    mothersGuardianContact: string;
    guardianDeclaration: boolean;
    religion: _Religion;
    fathersAadhaar: string;
    documentsChecklist: _DocumentsChecklist;
    annualFamilyIncome: string;
    handicapPercentage: [] | [bigint];
    fathersOccupation: string;
    previousExam: string;
    hasPenAndApaar: boolean;
    mothersAadhaar: string;
}): {
    bankAccountNumber: string;
    orphanedAndDestitute: boolean;
    studentEmail: string;
    hasEShikshakosh: boolean;
    subjects: SubjectSelection;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    caste: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: PassingDivision;
    studentPhone: string;
    religionOther: string;
    studentPen: string;
    photoUrl?: string;
    mothersOccupation: string;
    policeStation: string;
    fathersName: string;
    bankName: BankName;
    district: string;
    mothersName: string;
    state: State;
    fathersContact: string;
    aadharNumber: string;
    handicapType?: string;
    village: string;
    gender: Gender;
    physicallyHandicapped: boolean;
    category: Category;
    pinCode: string;
    previousRollNo: string;
    block: string;
    postOffice: string;
    mothersGuardianContact: string;
    guardianDeclaration: boolean;
    religion: Religion;
    fathersAadhaar: string;
    documentsChecklist: DocumentsChecklist;
    annualFamilyIncome: string;
    handicapPercentage?: bigint;
    fathersOccupation: string;
    previousExam: string;
    hasPenAndApaar: boolean;
    mothersAadhaar: string;
} {
    return {
        bankAccountNumber: value.bankAccountNumber,
        orphanedAndDestitute: value.orphanedAndDestitute,
        studentEmail: value.studentEmail,
        hasEShikshakosh: value.hasEShikshakosh,
        subjects: from_candid_SubjectSelection_n9(_uploadFile, _downloadFile, value.subjects),
        previousSchool: value.previousSchool,
        ifscCode: value.ifscCode,
        marksObtained: value.marksObtained,
        dateOfBirth: value.dateOfBirth,
        eShikshakoshNumber: value.eShikshakoshNumber,
        caste: value.caste,
        passingYear: value.passingYear,
        apparNumber: value.apparNumber,
        accountHolderName: value.accountHolderName,
        passingDivision: from_candid_PassingDivision_n15(_uploadFile, _downloadFile, value.passingDivision),
        studentPhone: value.studentPhone,
        religionOther: value.religionOther,
        studentPen: value.studentPen,
        photoUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.photoUrl)),
        mothersOccupation: value.mothersOccupation,
        policeStation: value.policeStation,
        fathersName: value.fathersName,
        bankName: from_candid_BankName_n17(_uploadFile, _downloadFile, value.bankName),
        district: value.district,
        mothersName: value.mothersName,
        state: from_candid_State_n19(_uploadFile, _downloadFile, value.state),
        fathersContact: value.fathersContact,
        aadharNumber: value.aadharNumber,
        handicapType: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.handicapType)),
        village: value.village,
        gender: from_candid_Gender_n21(_uploadFile, _downloadFile, value.gender),
        physicallyHandicapped: value.physicallyHandicapped,
        category: from_candid_Category_n23(_uploadFile, _downloadFile, value.category),
        pinCode: value.pinCode,
        previousRollNo: value.previousRollNo,
        block: value.block,
        postOffice: value.postOffice,
        mothersGuardianContact: value.mothersGuardianContact,
        guardianDeclaration: value.guardianDeclaration,
        religion: from_candid_Religion_n25(_uploadFile, _downloadFile, value.religion),
        fathersAadhaar: value.fathersAadhaar,
        documentsChecklist: value.documentsChecklist,
        annualFamilyIncome: value.annualFamilyIncome,
        handicapPercentage: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.handicapPercentage)),
        fathersOccupation: value.fathersOccupation,
        previousExam: value.previousExam,
        hasPenAndApaar: value.hasPenAndApaar,
        mothersAadhaar: value.mothersAadhaar
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
}): Stream {
    return "arts" in value ? Stream.arts : "commerce" in value ? Stream.commerce : "science" in value ? Stream.science : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    first: null;
} | {
    third: null;
} | {
    second: null;
}): PassingDivision {
    return "first" in value ? PassingDivision.first : "third" in value ? PassingDivision.third : "second" in value ? PassingDivision.second : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    finoPaymentBank: null;
} | {
    dakshinBiharGraminBank: null;
} | {
    indianPostPaymentBank: null;
} | {
    madhyaBiharGraminBank: null;
} | {
    stateBankOfIndia: null;
} | {
    unionBankOfIndia: null;
} | {
    punjabNationalBank: null;
}): BankName {
    return "other" in value ? BankName.other : "finoPaymentBank" in value ? BankName.finoPaymentBank : "dakshinBiharGraminBank" in value ? BankName.dakshinBiharGraminBank : "indianPostPaymentBank" in value ? BankName.indianPostPaymentBank : "madhyaBiharGraminBank" in value ? BankName.madhyaBiharGraminBank : "stateBankOfIndia" in value ? BankName.stateBankOfIndia : "unionBankOfIndia" in value ? BankName.unionBankOfIndia : "punjabNationalBank" in value ? BankName.punjabNationalBank : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    bihar: null;
} | {
    jharkhand: null;
}): State {
    return "other" in value ? State.other : "bihar" in value ? State.bihar : "jharkhand" in value ? State.jharkhand : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bc: null;
} | {
    sc: null;
} | {
    st: null;
} | {
    ebc: null;
} | {
    general: null;
}): Category {
    return "bc" in value ? Category.bc : "sc" in value ? Category.sc : "st" in value ? Category.st : "ebc" in value ? Category.ebc : "general" in value ? Category.general : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hinduism: null;
} | {
    other: null;
} | {
    christianity: null;
} | {
    buddhism: null;
} | {
    islam: null;
}): Religion {
    return "hinduism" in value ? Religion.hinduism : "other" in value ? Religion.other : "christianity" in value ? Religion.christianity : "buddhism" in value ? Religion.buddhism : "islam" in value ? Religion.islam : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    class09th: null;
} | {
    class10th: null;
} | {
    class11th: null;
} | {
    class12th: null;
}): Class {
    return "class09th" in value ? Class.class09th : "class10th" in value ? Class.class10th : "class11th" in value ? Class.class11th : "class12th" in value ? Class.class12th : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : "draft" in value ? ApplicationStatus.draft : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AdmissionForm_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdmissionForm): _AdmissionForm {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_BankName_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankName): _BankName {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function to_candid_Class_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Class): _Class {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_PassingDivision_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PassingDivision): _PassingDivision {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Religion_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Religion): _Religion {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_State_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: State): _State {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_Stream_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): _Stream {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_SubjectSelection_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectSelection): _SubjectSelection {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _class: Class;
    name: string;
    email: string;
    isStudent: boolean;
}): {
    _class: _Class;
    name: string;
    email: string;
    isStudent: boolean;
} {
    return {
        _class: to_candid_Class_n34(_uploadFile, _downloadFile, value._class),
        name: value.name,
        email: value.email,
        isStudent: value.isStudent
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: string;
    orphanedAndDestitute: boolean;
    studentEmail: string;
    hasEShikshakosh: boolean;
    subjects: SubjectSelection;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    caste: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: PassingDivision;
    studentPhone: string;
    religionOther: string;
    studentPen: string;
    photoUrl?: string;
    mothersOccupation: string;
    policeStation: string;
    fathersName: string;
    bankName: BankName;
    district: string;
    mothersName: string;
    state: State;
    fathersContact: string;
    aadharNumber: string;
    handicapType?: string;
    village: string;
    gender: Gender;
    physicallyHandicapped: boolean;
    category: Category;
    pinCode: string;
    previousRollNo: string;
    block: string;
    postOffice: string;
    mothersGuardianContact: string;
    guardianDeclaration: boolean;
    religion: Religion;
    fathersAadhaar: string;
    documentsChecklist: DocumentsChecklist;
    annualFamilyIncome: string;
    handicapPercentage?: bigint;
    fathersOccupation: string;
    previousExam: string;
    hasPenAndApaar: boolean;
    mothersAadhaar: string;
}): {
    bankAccountNumber: string;
    orphanedAndDestitute: boolean;
    studentEmail: string;
    hasEShikshakosh: boolean;
    subjects: _SubjectSelection;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    caste: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: _PassingDivision;
    studentPhone: string;
    religionOther: string;
    studentPen: string;
    photoUrl: [] | [string];
    mothersOccupation: string;
    policeStation: string;
    fathersName: string;
    bankName: _BankName;
    district: string;
    mothersName: string;
    state: _State;
    fathersContact: string;
    aadharNumber: string;
    handicapType: [] | [string];
    village: string;
    gender: _Gender;
    physicallyHandicapped: boolean;
    category: _Category;
    pinCode: string;
    previousRollNo: string;
    block: string;
    postOffice: string;
    mothersGuardianContact: string;
    guardianDeclaration: boolean;
    religion: _Religion;
    fathersAadhaar: string;
    documentsChecklist: _DocumentsChecklist;
    annualFamilyIncome: string;
    handicapPercentage: [] | [bigint];
    fathersOccupation: string;
    previousExam: string;
    hasPenAndApaar: boolean;
    mothersAadhaar: string;
} {
    return {
        bankAccountNumber: value.bankAccountNumber,
        orphanedAndDestitute: value.orphanedAndDestitute,
        studentEmail: value.studentEmail,
        hasEShikshakosh: value.hasEShikshakosh,
        subjects: to_candid_SubjectSelection_n40(_uploadFile, _downloadFile, value.subjects),
        previousSchool: value.previousSchool,
        ifscCode: value.ifscCode,
        marksObtained: value.marksObtained,
        dateOfBirth: value.dateOfBirth,
        eShikshakoshNumber: value.eShikshakoshNumber,
        caste: value.caste,
        passingYear: value.passingYear,
        apparNumber: value.apparNumber,
        accountHolderName: value.accountHolderName,
        passingDivision: to_candid_PassingDivision_n44(_uploadFile, _downloadFile, value.passingDivision),
        studentPhone: value.studentPhone,
        religionOther: value.religionOther,
        studentPen: value.studentPen,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        mothersOccupation: value.mothersOccupation,
        policeStation: value.policeStation,
        fathersName: value.fathersName,
        bankName: to_candid_BankName_n46(_uploadFile, _downloadFile, value.bankName),
        district: value.district,
        mothersName: value.mothersName,
        state: to_candid_State_n48(_uploadFile, _downloadFile, value.state),
        fathersContact: value.fathersContact,
        aadharNumber: value.aadharNumber,
        handicapType: value.handicapType ? candid_some(value.handicapType) : candid_none(),
        village: value.village,
        gender: to_candid_Gender_n50(_uploadFile, _downloadFile, value.gender),
        physicallyHandicapped: value.physicallyHandicapped,
        category: to_candid_Category_n52(_uploadFile, _downloadFile, value.category),
        pinCode: value.pinCode,
        previousRollNo: value.previousRollNo,
        block: value.block,
        postOffice: value.postOffice,
        mothersGuardianContact: value.mothersGuardianContact,
        guardianDeclaration: value.guardianDeclaration,
        religion: to_candid_Religion_n54(_uploadFile, _downloadFile, value.religion),
        fathersAadhaar: value.fathersAadhaar,
        documentsChecklist: value.documentsChecklist,
        annualFamilyIncome: value.annualFamilyIncome,
        handicapPercentage: value.handicapPercentage ? candid_some(value.handicapPercentage) : candid_none(),
        fathersOccupation: value.fathersOccupation,
        previousExam: value.previousExam,
        hasPenAndApaar: value.hasPenAndApaar,
        mothersAadhaar: value.mothersAadhaar
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mil?: string;
    sil?: string;
    extraSubject?: string;
    stream?: Stream;
    additionalSubject?: string;
    compulsoryGroup1?: string;
    compulsoryGroup2?: string;
    electiveSubjects: Array<string>;
}): {
    mil: [] | [string];
    sil: [] | [string];
    extraSubject: [] | [string];
    stream: [] | [_Stream];
    additionalSubject: [] | [string];
    compulsoryGroup1: [] | [string];
    compulsoryGroup2: [] | [string];
    electiveSubjects: Array<string>;
} {
    return {
        mil: value.mil ? candid_some(value.mil) : candid_none(),
        sil: value.sil ? candid_some(value.sil) : candid_none(),
        extraSubject: value.extraSubject ? candid_some(value.extraSubject) : candid_none(),
        stream: value.stream ? candid_some(to_candid_Stream_n42(_uploadFile, _downloadFile, value.stream)) : candid_none(),
        additionalSubject: value.additionalSubject ? candid_some(value.additionalSubject) : candid_none(),
        compulsoryGroup1: value.compulsoryGroup1 ? candid_some(value.compulsoryGroup1) : candid_none(),
        compulsoryGroup2: value.compulsoryGroup2 ? candid_some(value.compulsoryGroup2) : candid_none(),
        electiveSubjects: value.electiveSubjects
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Class): {
    class09th: null;
} | {
    class10th: null;
} | {
    class11th: null;
} | {
    class12th: null;
} {
    return value == Class.class09th ? {
        class09th: null
    } : value == Class.class10th ? {
        class10th: null
    } : value == Class.class11th ? {
        class11th: null
    } : value == Class.class12th ? {
        class12th: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
} {
    return value == Stream.arts ? {
        arts: null
    } : value == Stream.commerce ? {
        commerce: null
    } : value == Stream.science ? {
        science: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PassingDivision): {
    first: null;
} | {
    third: null;
} | {
    second: null;
} {
    return value == PassingDivision.first ? {
        first: null
    } : value == PassingDivision.third ? {
        third: null
    } : value == PassingDivision.second ? {
        second: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankName): {
    other: null;
} | {
    finoPaymentBank: null;
} | {
    dakshinBiharGraminBank: null;
} | {
    indianPostPaymentBank: null;
} | {
    madhyaBiharGraminBank: null;
} | {
    stateBankOfIndia: null;
} | {
    unionBankOfIndia: null;
} | {
    punjabNationalBank: null;
} {
    return value == BankName.other ? {
        other: null
    } : value == BankName.finoPaymentBank ? {
        finoPaymentBank: null
    } : value == BankName.dakshinBiharGraminBank ? {
        dakshinBiharGraminBank: null
    } : value == BankName.indianPostPaymentBank ? {
        indianPostPaymentBank: null
    } : value == BankName.madhyaBiharGraminBank ? {
        madhyaBiharGraminBank: null
    } : value == BankName.stateBankOfIndia ? {
        stateBankOfIndia: null
    } : value == BankName.unionBankOfIndia ? {
        unionBankOfIndia: null
    } : value == BankName.punjabNationalBank ? {
        punjabNationalBank: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: State): {
    other: null;
} | {
    bihar: null;
} | {
    jharkhand: null;
} {
    return value == State.other ? {
        other: null
    } : value == State.bihar ? {
        bihar: null
    } : value == State.jharkhand ? {
        jharkhand: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    bc: null;
} | {
    sc: null;
} | {
    st: null;
} | {
    ebc: null;
} | {
    general: null;
} {
    return value == Category.bc ? {
        bc: null
    } : value == Category.sc ? {
        sc: null
    } : value == Category.st ? {
        st: null
    } : value == Category.ebc ? {
        ebc: null
    } : value == Category.general ? {
        general: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Religion): {
    hinduism: null;
} | {
    other: null;
} | {
    christianity: null;
} | {
    buddhism: null;
} | {
    islam: null;
} {
    return value == Religion.hinduism ? {
        hinduism: null
    } : value == Religion.other ? {
        other: null
    } : value == Religion.christianity ? {
        christianity: null
    } : value == Religion.buddhism ? {
        buddhism: null
    } : value == Religion.islam ? {
        islam: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
